import dart from "./dart.svg";
import django from "./django.svg";
import docker from "./docker.svg";
import postgresssql from "./elephant.png";
import fastapi from "./fastapi.svg";
import flutter from "./flutter.svg";
import git from "./Git-Icon-1788C.svg";
import mysql from "./mysql.svg";
import nextjs from "./nextjs-transparent.svg";
import python from "./python-logo-only.png";
import react from "./react.svg";
import redis from "./redis-logo-full-color-rgb.svg";
import socketio from "./Socket-io.svg";
import swift from "./swift.svg";
import tailwind from "./tailwind.svg";
import ts from "./ts.svg";
import vercel from "./vercel.svg";
export { django, git, postgresssql, swift, redis, flutter, mysql, socketio, nextjs, fastapi, react, dart, tailwind, ts, vercel, docker, python };
